services:
  client:
    image: nginx
    restart: always
    container_name: gribok-portfolio
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
        - default

networks:
  default:
    external: true
    name: default_network