// Portfolio content — Григорий Муравенко (from CV)
window.PORTFOLIO = {
  projects: [
    { id: 'velum', category: 'Privacy · Network', title: 'Velum VPN', tag: 'продукт', year: '2024', url: 'vpnvelum.com',
      side: 'left',
      role: 'Founder · Core Engineer',
      links: [['Открыть сайт', 'https://vpnvelum.com/'], ['Бот в Telegram', 'https://t.me/VPNvelum_bot']],
      stack: ['Python', 'VLESS', 'Remnawave', 'PostgreSQL', 'Docker', 'Celery'],
      blurb: 'Собственный VPN-сервис с упором на скорость и устойчивость к блокировкам. 10\u00a0000+\u00a0пользователей.',
      problem: 'Готовые VPN либо медленные, либо легко режутся DPI. Нужна была высокая скорость без узнаваемой сигнатуры в трафике.',
      approach: 'Поднял сеть узлов на ядре VLESS с обфусцирующим транспортом и панелью Remnawave, автоматический выбор ближайшей локации и биллинг на Python.',
      result: 'Стабильный сервис с 10 000+ пользователей: скорость близка к нативной, устойчивость к блокировкам.',
      metrics: [['10 000+', 'пользователей'], ['VLESS', 'ядро'], ['24/7', 'аптайм']] },

    { id: 'multix', category: 'AI · Generation', title: 'Multix AI', tag: 'платформа', year: '2025', url: 'aimultix.com',
      side: 'right',
      role: 'Founder · Full-stack',
      links: [['Открыть сайт', 'https://aimultix.com/']],
      stack: ['Python', 'FastAPI', 'PostgreSQL', 'Celery', 'RabbitMQ'],
      blurb: 'Платформа для генерации контента с помощью ИИ — аналог Higgsfield. 500+ пользователей.',
      problem: 'Доступ к лучшим генеративным моделям разрознен: разные интерфейсы, ключи и оплаты, нет единого места.',
      approach: 'Собрал единый веб-интерфейс с очередями задач (Celery/RabbitMQ), маршрутизацией к моделям и биллингом.',
      result: 'Платформа с 500+ пользователями, генерирующая видео, фото и тексты из одного окна.',
      metrics: [['500+', 'пользователей'], ['Видео · Фото · Аудио', 'в одном окне'], ['S3', 'хранилище медиа']] },

    { id: 'aibots', category: 'AI · Telegram', title: 'Сеть ИИ-ботов', tag: 'продукт', year: '2025', url: '@ai_veo_bot · @sora2_aibot',
      side: 'left',
      role: 'Solo Engineer',
      links: [['@ai_veo_bot', 'https://t.me/ai_veo_bot'], ['@sora2_aibot', 'https://t.me/sora2_aibot']],
      stack: ['Python', 'aiogram', 'PostgreSQL', 'Celery', 'Docker'],
      blurb: 'Сеть Telegram-ботов для генерации видео, фото и аудио. Суммарная аудитория 60 000+ человек.',
      problem: 'Генеративные модели сложны для обычного пользователя — нужен максимально простой вход прямо в мессенджере.',
      approach: 'Запустил ботов (@ai_veo_bot, @sora2_aibot) с очередями генерации, оплатой и масштабированием под нагрузку.',
      result: 'Суммарная аудитория 60 000+ человек, тысячи генераций видео, фото и аудио ежедневно.',
      metrics: [['60 000+', 'аудитория'], ['видео · фото · аудио', 'генерация'], ['2', 'бота в сети']] },
  ],
  achievements: [
    ['10 000+', 'пользователей Velum VPN'],
    ['60 000+', 'аудитория ИИ-ботов'],
    ['Founder / CTO', '«Попутчик» · команда 6'],
    ['Яндекс', 'ML Cloud · SRE / DevOps', 'Backend Python'],
  ],
  talks: [
    ['МОШ 2023', 'Абсолютный победитель предпрофессиональной олимпиады'],
    ['НТО 2023', 'Призёр по направлению «Информационная безопасность»'],
    ['Яндекс 2024', 'Школа бэкенд-разработки на Python'],
  ],
  // Хронология: олимпиады · курсы · работа · проекты
  timeline: [
    { year: '2023',    type: 'олимпиада', place: 'МОШ',        title: 'Абсолютный победитель предпрофессиональной олимпиады' },
    { year: '2023',    type: 'олимпиада', place: 'НТО',        title: 'Призёр по направлению «Информационная безопасность»' },
    { year: '2024',    type: 'курс',      place: 'Яндекс',     title: 'Школа бэкенд-разработки на Python' },
    { year: '2024–25', type: 'работа',    place: 'Яндекс',     title: 'Бэкенд-стажировка на Python' },
    { year: '2025',    type: 'работа',    place: 'Яндекс',     title: 'DevOps / SRE junior' },
    { year: '2025',    type: 'проект',    place: 'ИИ-боты',    title: 'Сеть Telegram-ботов, аудитория 60 000+' },
    { year: '2025–26', type: 'работа',    place: '«Попутчик»', title: 'Founder / CTO — логистическая биржа, команда 6' },
    { year: '2026',    type: 'проект',    place: 'Velum VPN',  title: 'Запуск VPN-сервиса, 10 000+ пользователей' },
    { year: '2026',    type: 'проект',    place: 'Multix AI',  title: 'ИИ-платформа генерации контента' },
  ],
  stack: ['Python', 'Go', 'Java', 'FastAPI', 'Django', 'Flask', 'PostgreSQL', 'Docker', 'Celery', 'RabbitMQ'],
};
